In [1]:
import pandas as pd
import os
import numpy as np
from collections import Counter
#from functools import reduce
#import matplotlib.pyplot as plt

In [2]:
#path = '/Users/Ellen/Documents/Dokumenter/DTU/6.Semester/SocialData/Project/yelp_dataset'
path = 'C:\\Users\\prebe\\Documents\\Ellen\\Python\\Restaurant-Guide-master'
os.chdir(path)
os.getcwd()

'C:\\Users\\prebe\\Documents\\Ellen\\Python\\Restaurant-Guide-master'

In [3]:
df = pd.read_csv('yelp_reviews_RV_categories.csv')
#df = pd.read_json('yelp_academic_dataset_business.json', lines=True)

In [4]:
df = df.drop_duplicates(subset='text')
df.shape

(1674264, 21)

In [5]:
N = 1674264
MaxUsed = 100
df.shape
#(5177322, 23)
df = df.iloc[0:N]
df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,categories,hours,cat_kitchen,cat_type,user_id,review_stars,text,date,reviewlength,sentences
0,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,"Gastropubs, Food, Beer Gardens, Restaurants, B...","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...",American (Traditional),Food,93z0yh-sUpGZS-cSKu6xxA,5,Stopped in on a busy Friday night. Despite the...,2018-03-04 00:59:21,630,6
1,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,"Gastropubs, Food, Beer Gardens, Restaurants, B...","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...",American (Traditional),Food,Q_CZIvnsDHjpls-EPzzG7Q,2,Went there about 1 PM on a Monday. It wasn't ...,2018-08-14 05:22:00,885,11
2,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,"Gastropubs, Food, Beer Gardens, Restaurants, B...","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...",American (Traditional),Food,rqxTSFFj5fZNmabY1fmTlw,5,This was the place the be on Friday Night! If ...,2018-03-17 14:22:48,174,2
3,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,"Gastropubs, Food, Beer Gardens, Restaurants, B...","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...",American (Traditional),Food,vNPxlt5f50q0e2nVAScW3Q,4,Went to this place with my family over the wee...,2018-04-04 21:16:50,553,5
4,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,"Gastropubs, Food, Beer Gardens, Restaurants, B...","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...",American (Traditional),Food,eXRC79iX60xwA1UuGRuWNg,4,"Stopped on a midweek afternoon, and so glad th...",2018-04-28 19:17:04,841,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1674259,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,"Mexican, Bars, Nightlife, Tex-Mex, Restaurants","{'Monday': '0:0-0:0', 'Tuesday': '9:0-21:0', '...",Mexican,Bars,5DVF5ZRFccUJzp302O6iKw,3,Pretty good Tex Mex. I especially like their v...,2018-11-21 03:08:15,249,5
1674260,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,"Mexican, Bars, Nightlife, Tex-Mex, Restaurants","{'Monday': '0:0-0:0', 'Tuesday': '9:0-21:0', '...",Mexican,Bars,0ryxrnVmnS69A911dcEAOw,5,I've been going to Maudie's for years now and ...,2020-10-26 16:30:33,227,4
1674261,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,"Mexican, Bars, Nightlife, Tex-Mex, Restaurants","{'Monday': '0:0-0:0', 'Tuesday': '9:0-21:0', '...",Mexican,Bars,Q4z-fgH2kYfkN4cI1nEGpw,5,Maudie's is our go to Tex Mex spot in Austin -...,2019-12-15 23:44:43,377,3
1674262,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,"Mexican, Bars, Nightlife, Tex-Mex, Restaurants","{'Monday': '0:0-0:0', 'Tuesday': '9:0-21:0', '...",Mexican,Bars,N7LVqci26Lvu-rToIE_GRg,5,"For all Maudie's fan club, this new update is ...",2018-04-20 05:19:35,1866,36
1674263,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,"Mexican, Bars, Nightlife, Tex-Mex, Restaurants","{'Monday': '0:0-0:0', 'Tuesday': '9:0-21:0', '...",Mexican,Bars,TLGJNTc0vzW4s5-ym2RZxQ,2,Make sure you don't order nachos here! I get i...,2020-11-24 16:08:26,366,3

In [6]:
#Length of review
df['reviewlength'] = df['text'].str.len()

In [7]:
#antal sætninger
df['sentences'] = df["text"].str.count('\.')

In [8]:
#antal tal

# procentdel af store bogstaver

#procentdel af positive/negative meningsbærende ord --> Måske denne tages ud. Eller der laves liste med positive ord og en med negative


#gennemsnit længde af review
#one hot

In [9]:
from gensim.parsing.preprocessing import remove_stopwords
df.text.apply(remove_stopwords)

0          Stopped busy Friday night. Despite crowd, serv...
1          Went 1 PM Monday. It wasn't particularly busy,...
2          This place Friday Night! If you're looking bes...
3          Went place family weekend hike Boulder nice. T...
4          Stopped midweek afternoon, glad I did! One new...
                                 ...
1674259    Pretty good Tex Mex. I especially like variety...
1674260    I've going Maudie's years I love it. It's go-t...
1674261    Maudie's Tex Mex spot Austin - location lives ...
1674262    For Maudie's fan club, new update I rating Hil...
1674263    Make sure don't order nachos here! I it's "app...
Name: text, Length: 1674264, dtype: object

In [10]:
from gensim.utils import simple_preprocess
# Tokenize the text column to get the new column 'tokenized_text'
df['tokenized_text'] = [simple_preprocess(line, deacc=True) for line in df['text']]

In [11]:
from gensim.parsing.porter import PorterStemmer
porter_stemmer = PorterStemmer()
# Get the stemmed_tokens
df['stemmed_tokens'] = [[porter_stemmer.stem(word) for word in tokens] for tokens in df['tokenized_text']]

In [12]:
df['stemmed_text'] = df['stemmed_tokens'].apply(' '.join)

In [13]:
Word = []
WordCounter = Counter(" ".join(df["stemmed_text"]).split()).most_common(MaxUsed)
for j in range(len(WordCounter)):
    Word.insert(j,WordCounter[j][0])

In [14]:
Words = np.zeros((N,MaxUsed))


#for loop over rækker, og for loop over ordene i NWords. Hvis ord er der, sæt 1.
for index, row in df.iterrows():
    for i in range(np.size(Words, axis=1)):
        if Word[i] in df['stemmed_text'].iloc[index]:
            Words[index,i] = 1

In [15]:
#drop attributes with text
df = df.drop(['text','tokenized_text', 'stemmed_tokens',
       'stemmed_text'], axis=1)

In [16]:
df_words = pd.DataFrame(Words)

Names = list(range(0, MaxUsed))
ColNames = [str(n) for n in Names]

df_words.columns = ColNames
df_words

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1674259,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1674260,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1674261,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1674262,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
1674263,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [17]:
df = df.join(df_words)

df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,90,91,92,93,94,95,96,97,98,99
0,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1674259,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1674260,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1674261,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1674262,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
1674263,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [18]:
df['user_id'] = df['user_id'].astype('category')
df['business_id'] = df['business_id'].astype('category')

df['UserCat'] = df['user_id'].cat.codes
df['BusinessCat'] = df['business_id'].cat.codes

df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,92,93,94,95,96,97,98,99,UserCat,BusinessCat
0,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,121242,1377
1,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,332559,1377
2,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,674080,1377
3,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,716376,1377
4,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,513053,1377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1674259,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,74766,4969
1674260,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22620,4969
1674261,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,326705,4969
1674262,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,291127,4969
1674263,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,366064,4969

In [19]:
#f_feature = df.drop[['name','address', 'city', 'state', 'postal_code','latitude', 'longitude','attributes','categories','hours','cat_kitchen', 'cat_type','text', 'tokenized_text', 'stemmed_tokenz', 'stemmed_text']]
#df_feature = df[['stars', 'review_count','review_stars', 'reviewlength', 'sentences', '1','2','3','4','5','6']]

df_feature = df.drop(['business_id','name', 'address','city', 'state', 'postal_code', 'latitude',
       'longitude', 'attributes', 'categories',
       'hours', 'cat_kitchen', 'cat_type', 'user_id','date'], axis=1)
df_feature

,stars,review_count,review_stars,reviewlength,sentences,0,1,2,3,4,...,92,93,94,95,96,97,98,99,UserCat,BusinessCat
0,4.0,86,5,630,6,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,121242,1377
1,4.0,86,2,885,11,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,332559,1377
2,4.0,86,5,174,2,1.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,674080,1377
3,4.0,86,4,553,5,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,716376,1377
4,4.0,86,4,841,6,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,513053,1377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1674259,3.0,310,3,249,5,1.0,1.0,0.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,74766,4969
1674260,3.0,310,5,227,4,0.0,1.0,1.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22620,4969
1674261,3.0,310,5,377,3,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,326705,4969
1674262,3.0,310,5,1866,36,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,291127,4969
1674263,3.0,310,2,366,3,1.0,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,366064,4969

In [20]:
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest

In [21]:
model=IsolationForest(n_estimators=50, max_samples='auto', contamination=float(0.2),max_features=1.0)
model.fit(df_feature)

IsolationForest(contamination=0.2, n_estimators=50)

In [26]:
df['scores']=model.decision_function(df_feature)
df['anomaly']=model.predict(df_feature)

KeyboardInterrupt:

In [27]:
df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,94,95,96,97,98,99,UserCat,BusinessCat,scores,anomaly
0,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,0.0,0.0,0.0,0.0,0.0,0.0,121242,1377,0.060647,1
1,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,0.0,0.0,0.0,0.0,0.0,1.0,332559,1377,-0.019385,-1
2,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,0.0,0.0,0.0,0.0,0.0,0.0,674080,1377,0.049617,1
3,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,0.0,0.0,0.0,0.0,0.0,0.0,716376,1377,-0.001652,-1
4,6iYb2HFDywm3zjuRg0shjw,Oskar Blues Taproom,921 Pearl St,Boulder,CO,80302,40.017544,-105.283348,4.0,86,...,0.0,0.0,0.0,0.0,0.0,1.0,513053,1377,0.024127,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1674259,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,0.0,0.0,0.0,0.0,1.0,0.0,74766,4969,0.024248,1
1674260,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,0.0,0.0,0.0,0.0,0.0,0.0,22620,4969,0.061755,1
1674261,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,0.0,0.0,0.0,0.0,0.0,0.0,326705,4969,0.058651,1
1674262,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,1.0,0.0,1.0,0.0,0.0,1.0,291127,4969,-0.038669,-1
1674263,Q78fYV6B6P6GmX07YVgi4g,Maudie’s Hill Country,12506 Shops Pkwy,Bee Cave,TX,78738,30.304761,-97.937394,3.0,310,...,0.0,1.0,1.0,0.0,0.0,0.0,366064,4969,0.006419,1

In [23]:
path = 'C:\\Users\\prebe\\Documents\\Ellen\\Python\\Restaurant-Guide-master'
os.chdir(path)
os.getcwd()

'C:\\Users\\prebe\\Documents\\Ellen\\Python\\Restaurant-Guide-master'

In [24]:
csv_name = "AnomalyDetection.csv"
df.to_csv(csv_name, index=False)

In [25]:
#features:
#review_stars
#text
#most common words(are they in the review or not)
#reviewLength